FROM node:18-alpine3.16
# FROM oven/bun

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./

# RUN bun install -g @nestjs/cli
# RUN bun install
RUN npm install -g @nestjs/cli
RUN npm install

# Bundle app source
COPY . .

# Expose port 3000 
EXPOSE 3000

# Run the app
CMD ["npm", "run", "start:dev"]
# CMD ["bun", "run", "start:dev"]